From archlinux/base
ENV LANG C.UTF-8


RUN pacman -Syyu --noconfirm git python-chardet python-lxml \
        python-pyenchant python-beautifulsoup4 python-mako python-pyicu \
        python-waitress python-alembic bzr python-pip \
        python-webob mediainfo python-pytest python-dbus \
        python-pyqt5 xorg-server-xvfb python-requests python-qtawesome \
        python-zeroconf python-websockets qt5-webkit qt5-multimedia
