From fedora:29
ENV LANG C.UTF-8

RUN dnf install -y git python3-chardet python3-lxml bzr\
        python3-enchant python3-beautifulsoup4 python3-mako \
        python3-waitress python3-alembic python3-websockets \
        python3-webob mediainfo python3-pytest python3-dbus \
        python3-PyQt5 Xvfb python3-requests python3-QtAwesome \
        python3-pyicu python3-qt5-webkit
