name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: ["archlinux", "debian-stable", "debian-testing", "fedora-28", "fedora-29", "ubuntu-devel", "ubuntu-lts"]
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file ./dockerfiles/${{ matrix.tag }}/Dockerfile --tag simhnna/openlp:${{matrix.tag }}
